### PR TITLE
fix incorrect real ip for ssl-passthrough

### PR DESCRIPTION
**Pull request by hanxueluo**
1. this implemention can work together with
  'use-forwarded-for: "true"' and 'compute-full-forwarded-for: "true"'.

2. this fix breaks function of 'use-proxy-protocol: "true"'

3. this fix can not be cherrypicked to latest ingress-nginx,
   because 9af574a (>=0.26.0) refactor the real ip code in nginx.tmpl

Signed-off-by: Huanle Han <hanhuanle@caicloud.io>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by hanxueluo** [comment]
测试方法：
 1. configmap 参数 use-forwarded-headers: "true"
 2. 启动参数 --enable-ssl-passthrough
1 和 2 各开启关闭共四种组合。

四种组合下，以下四个命令都符合预期
curl -k  http://test.netlb.com
curl -k -H 'X-FORWARDED-FOR: 1.1.1.1' http://test.netlb.com
curl -k  https://test.netlb.com
curl -k -H 'X-FORWARDED-FOR: 1.1.1.1' https://test.netlb.com

**Comment by hanxueluo** [comment]
@hicaistar @VincentGuoCQ

**Comment by hanxueluo** [comment]
合入该修改了。请 @archever 跟踪下后续测试验证。

**Comment by archever** [comment]
> 合入该修改了。请 @archever 跟踪下后续测试验证。

ok

**Pull request merged**
