### PR TITLE
feat(canary): support use cookie value and pattern

### PR DESCRIPTION
**Pull request by whalecold**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by whalecold** [comment]
ping @hanxueluo @qianlei90

**Comment by hanxueluo** [comment]
LGTM

**Comment by whalecold** [comment]
@hezhizhen

**Comment by hezhizhen** [comment]
LGTM

**Pull request merged**
